name: boilerplate
description: A flutter boilerplate project created using MobX and Provider.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # A
  another_flushbar: ^1.12.29
  # B
  # C
  cupertino_icons: ^1.0.5
  # D
  dio: ^5.1.1
  # E
  event_bus: ^2.0.0
  # F
  flutter_mobx: ^2.0.6+5
  flutter_lints: ^5.0.0
  # G
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  # H
  http: ^1.3.0
  # I
  intl: ^0.19.0
  # J
  # K
  # L
  # M
  mobx: ^2.1.4
  # N
  # O
  # P
  path_provider: ^2.0.14
  # Q
  # R
  # S
  shared_preferences: ^2.1.0
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  shadcn_flutter: ^0.0.34
  # T
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  hive_generator: ^2.0.1
  fpdart: ^1.1.1
  uuid: ^4.5.1
  synchronized: ^3.3.1
  bcrypt: ^1.1.3
  dart_style: ^2.3.8
  crypto: ^3.0.6
  pointycastle: ^4.0.0
  skeletonizer: ^1.4.3
  file_picker: ^10.1.2
  image_picker: ^1.1.2
  mime: ^2.0.0
  go_router: ^15.1.1
  provider: ^6.1.5
  data_widget: ^0.0.2
  gap: ^3.0.1
  email_validator: ^3.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  dartz: ^0.10.1
  awesome_notifications: ^0.10.0
  # Y
  # Z

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.14.3
  mobx_codegen: ^2.2.0
  build_runner: ^2.4.15
  analyzer: ^6.11.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter_icons:
  image_path: "assets/icons/ic_app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: ProductSans
      fonts:
        # Regular (w400)
        - asset: assets/fonts/Helvetica.ttf
          weight: 400
        - asset: assets/fonts/Helvetica-Oblique.ttf
          weight: 400
          style: italic

        # Light (w300)
        - asset: assets/fonts/helvetica-light.ttf
          weight: 300

        # Medium (w600)
        - asset: assets/fonts/helvetica-rounded-bold.otf
          weight: 600

        # Bold (w700)
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
          weight: 700
          style: italic

        # ExtraBold (w700)
        - asset: assets/fonts/helvetica-compressed.otf
          weight: 600
