// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6oBGFFKB1rRUJDk-nYxrIo5q5Pf6OcM',
    appId: '1:197884097948:web:e2b618bc387ed866944459',
    messagingSenderId: '197884097948',
    projectId: 'testauthflutter-356d6',
    authDomain: 'testauthflutter-356d6.firebaseapp.com',
    storageBucket: 'testauthflutter-356d6.firebasestorage.app',
    measurementId: 'G-LZN1NXRTZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcFaNNYAjdXso1pu9A713jjCBLZv7DFOo',
    appId: '1:197884097948:android:47228ac385a61c68944459',
    messagingSenderId: '197884097948',
    projectId: 'testauthflutter-356d6',
    storageBucket: 'testauthflutter-356d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAaKVoacwf004bFvikBD8MrobiMn6m9Hk',
    appId: '1:197884097948:ios:8cb9a81e3d58ff59944459',
    messagingSenderId: '197884097948',
    projectId: 'testauthflutter-356d6',
    storageBucket: 'testauthflutter-356d6.firebasestorage.app',
    iosClientId: '197884097948-a3lalb2s6sm3377km76bloshokjr1ipu.apps.googleusercontent.com',
    iosBundleId: 'com.iotecksolutions.flutterBoilerplateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAaKVoacwf004bFvikBD8MrobiMn6m9Hk',
    appId: '1:197884097948:ios:8cb9a81e3d58ff59944459',
    messagingSenderId: '197884097948',
    projectId: 'testauthflutter-356d6',
    storageBucket: 'testauthflutter-356d6.firebasestorage.app',
    iosClientId: '197884097948-a3lalb2s6sm3377km76bloshokjr1ipu.apps.googleusercontent.com',
    iosBundleId: 'com.iotecksolutions.flutterBoilerplateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ6oBGFFKB1rRUJDk-nYxrIo5q5Pf6OcM',
    appId: '1:197884097948:web:8b37f9f7b817feaf944459',
    messagingSenderId: '197884097948',
    projectId: 'testauthflutter-356d6',
    authDomain: 'testauthflutter-356d6.firebaseapp.com',
    storageBucket: 'testauthflutter-356d6.firebasestorage.app',
    measurementId: 'G-B8T1JJDERY',
  );

}